stages:
  - build
 # - test-backend
  - ui-test
  - deploy

jobs:
  include:
    # Builds the whole application (front- and backend) into a single jar
    # Then builds docker image and pushes it DockerHub 
    - stage: build
      language: java
      services:
        - docker
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - (cd backend/; mvn package)
        - (cd backend/; docker build -f Dockerfile -t fcc-application-docker .)
        - docker tag fcc-application-docker $DOCKER_USERNAME/$DOCKER_REPONAME
        - docker push $DOCKER_USERNAME/$DOCKER_REPONAME
        - docker logout

    #  Runs UI test with the previously builded docker container
    - stage: ui-test
      language: node_js
      node_js:
        - "10"
      dist: trusty
      sudo: required
      services:
        - mysql
        - docker
      addons:
        firefox: latest
        apt:
          sources:
          - google-chrome
          packages:
          - google-chrome-stable fluxbox
      before_install:
        - mysql -u root --password="" < travis.sql
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      install:
        - (cd frontend/; npm install; cd ../)
        - sudo chmod +x ./wait-for-it.sh
        - docker run -p 8080:8080 -d $DOCKER_USERNAME/$DOCKER_REPONAME
      before_script:
        - cd frontend
        - npm start &
        - cd ../
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
        - fluxbox >/dev/null 2>&1 &
      script:
        - sudo ./wait-for-it.sh localhost:8080
        - sudo ./wait-for-it.sh localhost:3000
        - "./node_modules/.bin/cucumber-js.cmd --world-parameters \"{\\\"browser\\\": \\\"firefox\\\"}\""

    # Deploys the docker container to heroku (prod)
    - stage: deploy
      language: java
      services:
        - docker
      provider: heroku
      before_script:
        - heroku container:login
      script:
        - cd backend/
        - mvn package
        - docker build -f Dockerfile -t fcc-application-docker .
        - docker tag fcc-application-docker registry.heroku.com/flashcardcommunity/web
        - docker push registry.heroku.com/flashcardcommunity/web
        - heroku container:release web -a flashcardcommunity

       