stages:
  - build
  - test-backend
  - test-frontend

jobs:
  include:
    - stage: build
      language: java
      script:
        - (cd backend/; mvn package)
    - stage: test-backend
      language: java
      script:
        - (cd backend/; mvn test)
    - stage: test-frontend
      language: node_js
      script:
       -  (cd frontend/; npm test)