stages:
  - build
 # - test-backend
  - ui-test
 # - deploy

jobs:
  include:
    # Builds the whole application (front- and backend) into a single jar
    # Then builds docker image and pushes it DockerHub
    - stage: build
      language: java
      services:
        - docker
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - (cd backend/; mvn package)
        - (cd backend/; docker build -f Dockerfile -t fcc-application-docker .)
        - docker tag fcc-application-docker $DOCKER_USERNAME/$DOCKER_REPONAME
        - docker push $DOCKER_USERNAME/$DOCKER_REPONAME
        - docker logout
#    - stage: test-backend
#      language: java
#      script:
#        - (cd backend/; mvn test)
    # Runs UI tests with Tescafé, therefor starts the application and a mysql server
    - stage: ui-test
      language: node_js
      node_js:
        - "10"
      dist: trusty
      sudo: required
      services:
        - mysql
        - docker
      addons:
        firefox: latest
        apt:
          sources:
          - google-chrome
          packages:
          - google-chrome-stable fluxbox
      before_install:
        - mysql -u root --password="" < travis.sql
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      install:
        - (cd frontend/; npm install; cd ../)
        - docker run -p 8080:8080 -d $DOCKER_USERNAME/$DOCKER_REPONAME 
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
        - fluxbox >/dev/null 2>&1 &
        - sudo ./wait-for-it.sh localhost:8080 -- echo "FCC-App is now running"
      script:
       -  sudo curl localhost:8080